version: "3.9"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "8082:8082"
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls
      - ./rtmp/logs:/usr/local/nginx/logs
      - ./rtmp/nginx.conf:/etc/nginx/nginx.conf