// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: chats.sql

package db

import (
	"context"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (
    user_id,anonym, message,session_id,room_id
) VALUES (
             $1, $2 ,$3,$4,$5
         )
    RETURNING id, user_id, anonym, message, session_id, room_id, created_at
`

type CreateChatParams struct {
	UserID    int64  `json:"user_id"`
	Anonym    string `json:"anonym"`
	Message   string `json:"message"`
	SessionID string `json:"session_id"`
	RoomID    int64  `json:"room_id"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, createChat,
		arg.UserID,
		arg.Anonym,
		arg.Message,
		arg.SessionID,
		arg.RoomID,
	)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Anonym,
		&i.Message,
		&i.SessionID,
		&i.RoomID,
		&i.CreatedAt,
	)
	return i, err
}
