// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Chat struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Anonym    string    `json:"anonym"`
	Message   string    `json:"message"`
	SessionID string    `json:"session_id"`
	RoomID    int64     `json:"room_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Room struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	RoomName  string    `json:"room_name"`
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	ID        string    `json:"id"`
	Members   string    `json:"members"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID             int64     `json:"id"`
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
}
